hoover.nomad
After this we should be able to remove all `chown -R 1000:1000` lines from the [installation manual](https://hackmd.io/MeBET7lQSd2mBOv7vlhwWw#).
=> Change elasticsearch data directory permissions when container starts

Readme.md, collection.nomad, hoover.nomad, liquid.nomad, liquid.py, repos/.gitignore, repos/clone.sh, repos/nuke.sh
Permit working on hoover/search, hoover/snoop and liquidinvestigations/core.
First clone the repos:
```shell
cd repos
./clone.sh
```
Then add this config flag:
liquid.ini
```
[liquid]
mount_local_repos = true
```
Finally re-deploy.
=> Clone & nuke hoover and liquidinvestigations repos

Readme.md, liquid.py
This patch encapsulates the configuration resolution as a class. It also changes the way custom jobs are defined - instead of listing them in an `extra_jobs` setting, they are now defined as separate sections, e.g.
```ini
[job:foo]
template = local/foo.nomad
```
=> Refactor the configuration logic

liquid.py, liquid_node/commands.py
Set the log level based on `liquid_debug`. Be more conservative with log messages when waiting on health checks.
=> Log levels and messages

vagrant/deploy-demo
The old version is in a better position to tear itself down, so let's give it a fair chance.
=> Do `git pull` after `liquid halt`

liquid_node/commands.py
So that it doesn't clash with the liquiddemo.org admin account.
Fixes https://github.com/liquidinvestigations/node/issues/89
=> Use a less obvious admin username

liquid_node/configuration.py, liquid_node/jobs.py
- allow relative paths (previously the mount paths had to be absolute)
- log warning when a repository path did not exist and do not mount it
=> development repositories mount fixes

liquid_node/commands.py, templates/rocketchat.nomad
* Users have to log in twice, but it's just clicking on buttons, not entering credentials, so it's pretty painless.
* If `foo` is logged in and chatting in rocketchat, and the person logs out from liquid, then logs in with a different account `bar` in the same browser, rocketchat will still believe that `foo` was logged in, because nobody automatically logged him out from rocketchat. https://github.com/liquidinvestigations/node/issues/105
=> Use authproxy for Rocket.Chat

templates/hoover.nomad
A spiegel VM of mine has a long name and nginx was exiting due to an error about the `server_name_hash_bucket_size `
=> increase server_name_hash_bucket_size to 128

liquid_node/commands.py, liquid_node/import_from_docker.py
Simplify migrating:
- don't overwrite liquid.ini, just ask the user to edit it
- link/copy/move the collection source data too
=> importfromdockersetup: Don't overwrite ini file; link collections too

vagrant/provision-liquid.sh
When running `vagrant up --provider=vmck` an error would show up saying that a symlink can't be synced through rsync, but there was no point in having synced symlinks.
=> Remove symlinks creation from vagrant/provision-liquid.sh

liquid_node/commands.py
This will avoid an Elasticsearch crash down the line.
This assumes that all services will run on the current
machine.
=> Check vm.max_map_count kernel param before deploy

liquid_node/commands.py, liquid_node/nomad.py, templates/collection.nomad
- also take into account collection jobs when running `./liquid resources`
- print EphemeralDiskMB in `./liquid resources`
- use the macros to lower disk requirements for collection jobs
=> Lower disk restrictions

templates/rocketchat.nomad
Rocketchat is getting kicked out of traefik intermittently (404 errors), maybe healthchecks are failing because of low memory, now that it has nonzero users. Let's be generous with it.
=> Increase Rocket.Chat memory from 700M to 1.5G

templates/_lib.hcl, templates/rocketchat.nomad, versions.ini
Rocketchat creates a persistent connection per browser, and 4 threads is not enough, how about 150?
https://github.com/Pylons/waitress/issues/235
=> More threads for rocketchat authproxy

templates/_lib.hcl
Authproxy should restart more aggressively. We run a limited number of them, and they are super lightweight (Flask apps with a couple of views), so it won't hurt performance much. I find myself waiting for nomad to reschedule authproxy often, and this should help.
I think these settings mean "Within a 1 minute window, allow 4 restarts, and wait 5 seconds before a restart. If that fails, instead of making a new alloc, reuse this one." Reference: https://www.nomadproject.io/docs/job-specification/restart.html
By the way, this is running on Rubidium right now, it's helping me debug Hypothesis.
=> Agressive restarts for authproxy

liquid_node/commands.py
This patch adds a couple of options:
* `--no-secrets` so that deploy makes no attempt to configure vault secrets or db passwords;
* `--no-checks` to skip waiting for healthchecks.
They are designed to help with configuration changes (e.g. number of snoop workers or elasticsearch memory) or hotfixes for critical services that are down (e.g. hoover or rocketchat). The assumption is that a full deploy was already made and we just want to push configuration changes to Nomad.
Skipping healthchecks can be especially useful - if the liquid bundle has a single failed database job, e.g. for a snoop collection, the healthchecks fail during deploy, which blocks deployment of any apps.
I think that ultimately the solution is to massively simplify this deployment process and use other strategies (e.g. …
=> Options to skip secrets and checks

.gitignore, local_jobs/.gitignore, local_jobs/.gitkeep
So that users can create their own git repo in there with their own `.gitignore` file.
=> Remove the `.gitignore` from `local_jobs`

liquid
Just to avoid the error message for QA and Production until we replace the liquid wrapper
=> Removed -q (currently not supported using Ubuntu)

templates/drone.nomad
1 commit https://github.com/drone/drone-vault/commit/309888e6035a7fa3ccb5bba5c3588c2433fec192
only latest docker tags https://hub.docker.com/r/drone/vault/tags
All history rewritten...
=> fix drone secret key name for plugin

templates/_lib.hcl
I wrongly assumed we'd be running a loki for each nomad node, practical experience from liquiddemo.org shows otherwise.
=> Send logs to the central loki server

templates/nextcloud-setup.sh
php occ files:scan doesn't work without either --all or an user-id.
=> Fix migration script file scan

templates/codimd.nomad, templates/rocketchat.nomad
Because they randomly enter a `connection refused` state and stay there...
=> add check_restart for javascript servers

liquid_node/commands.py
Because, on some distros, normal users can't run `sysctl`.
=> Read file in `/proc` instead of running sysctl

templates/codimd.nomad
Apparently codimd generates URLs with port 3000 unless we set this.
=> Set codimd port for the url

examples/liquid.ini, templates/nextcloud-migrate.nomad, templates/nextcloud-setup.sh
To avoid CI timeouts like https://jenkins.liquiddemo.org/liquidinvestigations/node/1067/1/3 and reduce total CI runtime.
=> Update deploy timeouts

Readme.md
closes CRJI/EIC#550
I exchanged the links because I think that's the most recent Documentation on how to set up the UI locally.
=> Exchanged link to Hoover-UI setup in Readme

production-versions.ini, staging-versions.ini
Version 0.0.1 had to download a file after the container was created (required connection to the internet). In 0.0.2 the download is done during container creation. 
There is also a new status endpoint to get information about the service.
=> Update image-classification-service to 0.0.2

templates/nextcloud28-entrypoint.sh
Fix error where nextcloud would delete groups when a user logs in. This was due to a setting that removes groups which are not available through the oauth profile.
=> fix nextcloud deleting groups on login
