- nomad/Readme.md
I think this covers the issues I ran into.
> improve the nomad readme

- .gitignore
- Readme.md
- collection-testdata.nomad
- hoover-ui.nomad
- hoover.nomad
- liquid.nomad
- liquid.py
Fixes https://github.com/liquidinvestigations/node/issues/12
> Config parser and deploy command

- liquid.nomad
- liquid.py
> Customize public http port

- Readme.md
- liquid.py
- liquid_node/commands.py
- liquid_node/configuration.py
- liquid_node/vault.py
Remove `initializevault` and `unsealvault`, they are being added in `cluster` with https://github.com/liquidinvestigations/cluster/pull/15.
> Don't worry about vault lifecycle, just need token

- liquid_node/configuration.py
And simplify the code path to read the secrets file.
> Relative path for vault secrets

- liquid
- requirements.in
- requirements.txt
Auto-recreate the venv if it's out of date, and provide a sane path to add new dependencies and update their versions.
> Manage the venv

- examples/liquid.ini
- liquid_node/commands.py
- liquid_node/configuration.py
- liquid_node/jobs.py
- templates/collection.nomad
- templates/hoover.nomad
- templates/liquid.nomad
- vagrant/ci-liquid.ini
- vagrant/provision-liquid.sh
Https is not supported yet in this version.
> Traefik with http

- templates/liquid.nomad
- Updated liquid nomad file with new env variables
> [#37] Links to apps on the homepage

- .drone.yml
- templates/_lib.hcl
- templates/collection-migrate.nomad
- templates/collection.nomad
- templates/dokuwiki-migrate.nomad
- templates/dokuwiki.nomad
- templates/drone.nomad
- templates/hoover-migrate.nomad
- templates/hoover-ui.nomad
- templates/hoover.nomad
- templates/liquid.nomad
- templates/nextcloud.nomad
- templates/rocketchat.nomad
- templates/zipkin.nomad
- vagrant/deploy-demo
- vagrant/deploy-vmck
- vagrant/launch-deploy-demo-container
The drone pipeline runs a `library/docker` container that commands the host to run `python3` container with `--detach` that will run `./liquid deploy`.
> Deploy to demo server

- templates/hoover-migrate.nomad
actual fix has been merged in https://github.com/hoover/search/pull/63
> fix hoover static files

- liquid_node/collections.py
- liquid_node/commands.py
Needed for https://github.com/CRJI/EIC/issues/198
> push collections titles from liquid.ini

- templates/collection-migrate.nomad
- templates/collection.nomad
So that we have access to ocr and gpghome.
> Mount the entire collection folder

- liquid_node/vault.py
Oh hey, @gabriel-v, forgot about this branch. Do you still need to wait for vault in your PR? If not, just close this.
> Wait for vault to return a happy answer

- liquid.py
- liquid_node/commands.py
Fixes https://github.com/liquidinvestigations/node/issues/109
> `deletecollection` command

- liquid.py
- liquid_node/commands.py
- liquid_node/jobs/__init__.py
- liquid_node/nomad.py
- vagrant/provision-liquid.sh
Print memory, disk IO and ram required to deploy.
> Deployment stats

- liquid_node/jsonapi.py
https://github.com/CRJI/EIC/issues/266
> fix crash on empty response

- vagrant/Vagrantfile
- vagrant/deploy-vmck
- vagrant/provision-liquid.sh
- vagrant/wait-cluster.sh
This should fix the intermittent test failures we keep seeing with the integration test.
> Use the new wait command for cluster

- examples/liquid.ini
- liquid_node/configuration.py
- templates/hoover.nomad
closes https://github.com/liquidinvestigations/node/issues/143
> Configure elasticsearch memory

- examples/liquid.ini
- liquid_node/configuration.py
- templates/_lib.hcl
- templates/authdemo.nomad
- templates/collection-migrate.nomad
- templates/collection.nomad
- templates/drone.nomad
- templates/hoover-migrate.nomad
- templates/hoover-ui.nomad
- templates/hoover.nomad
- templates/liquid.nomad
- templates/nextcloud-migrate.nomad
- templates/nextcloud.nomad
- templates/rocketchat-migrate.nomad
- versions.ini
Specify the full docker image name, maybe you want to run a fork of your own.
> Refactor docker image override

- templates/rocketchat-caboose.py
- templates/rocketchat-migrate.nomad
- versions.ini
Bump versions; get rid of caboose image
> Versions jul18

- liquid_node/commands.py
- templates/_lib.hcl
We seem to reschedule too many batch jobs.
> Use default reschedule

- Readme.md
- examples/liquid.ini
- liquid_node/configuration.py
- templates/liquid.nomad
- versions.ini
Depends on https://github.com/liquidinvestigations/core/pull/60, but can be merged safely before.
> Log out all users; accept only admins

- examples/liquid.ini
- liquid_node/configuration.py
- templates/drone.nomad
This code is already running on `fritz` so you can consider it tested :)
> Set env vars for drone about docker local registry

- liquid_node/commands.py
- templates/nextcloud-migrate.nomad
- templates/nextcloud-setup.sh
- templates/nextcloud.nomad
- versions.ini
the PR puts the admin username and passwords into the nextcloud container via env variable and updates the version of `liquid-nextcloud` to be used.
It also puts the admin password into vault.
> Nextcloud admin

- .drone.yml
- templates/drone.nomad
- vagrant/Vagrantfile
- versions.ini
Now there is only one vmck on port 9995
> Bump vmck to v0.3.0

- templates/collection.nomad
> snoop worker: expose the flower UI port

- examples/liquid.ini
- liquid_node/configuration.py
- templates/liquid.nomad
- versions.ini
Goes together with https://github.com/liquidinvestigations/core/pull/66.
TODO:
> Auto logout after a specified time

- Readme.md
- examples/liquid.ini
- liquid.py
- liquid_node/commands.py
- liquid_node/configuration.py
- liquid_node/jobs/__init__.py
- liquid_node/jobs/dokuwiki.py
- liquid_node/jobs/hoover.py
- liquid_node/jobs/liquid.py
- liquid_node/jobs/nextcloud.py
- liquid_node/jobs/rocketchat.py
- vagrant/liquid-apps.ini
- vagrant/provision-liquid.sh
Issue https://github.com/CRJI/EIC/issues/271
> Allow customisation of the apps started on deploy

- liquid_node/jobs/__init__.py
- repos/clone.sh
- templates/hoover-ui.nomad
- templates/hoover.nomad
Useful with https://github.com/hoover/ui/pull/68 and https://github.com/hoover/search/pull/90
> Fix Hypothesis embed in Hoover

- .drone.yml
- vagrant/Vagrantfile
Add name for ci steps that use VMCK
> Name on vmck

- templates/nextcloud-setup.sh
The PR just installs the contacts app. One can import a `.vcf` file from the web interface. 
Additionally I have added a scan to the startup routine, for when one kills nextcloud by removing `volumes/nextcloud`
> Nextcloud contacts

- templates/collection.nomad
- templates/hoover.nomad
This should reduce our alloc count by a lot
> replace nginx with fabiolb

- templates/_lib.hcl
- templates/collection-deps.nomad
- templates/collection.nomad
- templates/dokuwiki-migrate.nomad
- templates/dokuwiki.nomad
- templates/drone.nomad
- templates/hoover-deps.nomad
- templates/hoover-ui.nomad
- templates/hoover.nomad
- templates/hypothesis-usersync.nomad
- templates/hypothesis.nomad
- templates/ingress.nomad
- templates/liquid.nomad
- templates/nextcloud-migrate.nomad
- templates/nextcloud.nomad
- templates/rocketchat-migrate.nomad
- templates/rocketchat.nomad
- templates/zipkin.nomad
Capture authproxy logs for now, but I think we should add `{{ promtail_task() }}` to all groups.
> Run `promtail` to send logs to Loki

- templates/_lib.hcl
- vagrant/Vagrantfile
- vagrant/deploy-vmck
- versions.ini
Depends on https://github.com/liquidinvestigations/authproxy/pull/14
TODO: tag an authproxy version before merging this.
> Tell authproxy about consul

- templates/hoover-deps.nomad
> elasticsearch 6.8.3

- templates/_lib.hcl
- templates/codimd.nomad
- templates/nextcloud.nomad
- vagrant/Vagrantfile
Temporary fix until we resolve https://github.com/liquidinvestigations/authproxy/issues/21
> Authproxy memory

- examples/liquid.ini
- liquid_node/configuration.py
- templates/hoover-deps.nomad
- vagrant/Vagrantfile
One master node, multiple data nodes, all load-balanced by fabio.
It just works(tm)
> run elasticsearch data nodes

- templates/nextcloud.nomad
here:
https://docs.nextcloud.com/server/15/admin_manual/installation/system_requirements.html
> Set 512mb for nextcloud as recommended

- docs/Hoover.md
- liquid.py
- liquid_node/commands.py
- liquid_node/configuration.py
- liquid_node/jobs/nextcloud.py
- templates/collection-ocr.nomad
- templates/nextcloud-migrate.nomad
- templates/nextcloud-periodic.nomad
- vagrant/provision-liquid.sh
https://github.com/liquidinvestigations/tesseract-batch
This won't pick up files inside archives, attachments or anywhere else not directly under `/data`.
> New command to launch OCR job

- examples/liquid.ini
- liquid_node/configuration.py
- templates/hypothesis.nomad
- templates/nextcloud.nomad
> configure memory for h and nc

- templates/collection-ocr.nomad
- versions.ini
Will set this up on demo in 30min.
> tag new versions for everything

- templates/hypothesis.nomad
closes https://github.com/CRJI/EIC/issues/385
> add script healthcheck for hypothesis workers

- templates/hoover-deps.nomad
The defaults are `10s` interval and a `7d` history.
> collect es stats every 30s for 1 month

- templates/hoover-deps.nomad
Tika `1.20` still occasionally hangs
> use check_restart on tika

- templates/_lib.hcl
- templates/codimd.nomad
- templates/collection-deps.nomad
- templates/collection-ocr.nomad
- templates/collection.nomad
- templates/dokuwiki.nomad
- templates/drone.nomad
- templates/hoover-deps.nomad
- templates/hoover-system.nomad
- templates/hoover-ui.nomad
- templates/hoover.nomad
- templates/hypothesis-usersync.nomad
- templates/hypothesis.nomad
- templates/ingress.nomad
- templates/liquid.nomad
- templates/nextcloud-migrate.nomad
- templates/nextcloud-periodic.nomad
- templates/nextcloud.nomad
- templates/rocketchat-migrate.nomad
- templates/rocketchat.nomad
- templates/zipkin.nomad
Nomad is already collecting logs, as well as dockerd.
> remove promtail

- templates/collection-deps.nomad
> rabbitmq management and http health checks

- templates/hoover-deps.nomad
So that we can snapshot indexes into it.
> Register an ES snapshot repo

- templates/nextcloud-setup.sh
Resolved the JSON parse error in the Nextcloud Migrate Job.
Added Nextcloud Default Apps (#432)
> Resolved NC Migrate Error + NC Default Apps

- liquid.py
- liquid_node/backup.py
- vagrant/provision-liquid.sh
- versions.ini
Missing: a routine for hypothesis.
> Backup and restore apps

- liquid_node/backup.py
- liquid_node/jsonapi.py
- templates/hypothesis.nomad
The restore Process got its own [function](https://github.com/liquidinvestigations/node/compare/hypothesis-backup-restore#diff-bf5271dce6a9f8ba053979c452ab36dcR371) instead of using `restore_collection_es` because I liked it better than all the `if` statements that would have been necessary if we did it in the same function. But if you want it in the same function, just let me know.
Because [this](https://github.com/liquidinvestigations/node/compare/hypothesis-backup-restore#diff-bf5271dce6a9f8ba053979c452ab36dcR332-R338) way of resetting and closing the index wasn't possible without creating a new manage.py with the respective commands, I just [delete the old index](https://github.com/liquidinvestigations/node/compare/hypothesis-backup-restore#diff-bf5271dce6a9f8ba053979c452ab36dcR404-R40 …
> Hypothesis backup & restore

- templates/hoover.nomad
- versions.ini
Run pdf2pdfocr alongside the per-image OCR.
> Tesseract ocr task

- Pipfile
- Pipfile.lock
- docs/Maintenance.md
- liquid.py
- liquid_node/backup.py
- liquid_node/commands.py
- vagrant/provision-liquid.sh
I changed the old argparse to the click in liquid.py. I opened a new branch because the old one was behind the master by too many commits!
Fixes #43
> Change from argparse to click

- liquid_node/configuration.py
- templates/liquid.nomad
Having all urls and status for apps in a single json, that is passed to nomad and then to core.
> Urls as json for homepage

- bin/periodic-backup.sh
- docs/Maintenance.md
Script and documentation added. First part of CRJI/EIC#689
> Create a periodic backup script

- autoreload
- docs/Development.md
- liquid_node/commands.py
- liquid_node/jobs/__init__.py
- templates/codimd.nomad
- templates/hoover-deps.nomad
- templates/hoover-nginx.nomad
- templates/hoover-workers.nomad
- templates/hoover.nomad
- templates/hypothesis.nomad
- templates/liquid.nomad
Script to auto-reload and redeploy on code changes.
> Autoreload

- liquid_node/util.py
> Mute retries

- docs/Development.md
- liquid_node/configuration.py
- production-versions.ini
- staging-versions.ini
- templates/hoover-deps.nomad
- templates/hoover-workers.nomad
- templates/hoover.nomad
- testing-versions.ini
> Pdf preview service

- examples/liquid.ini
- liquid_node/configuration.py
- production-versions.ini
- staging-versions.ini
- templates/hoover-deps.nomad
- templates/hoover-workers.nomad
- templates/hoover.nomad
- testing-versions.ini
> Object detection service

- liquid_node/configuration.py
- liquid_node/jobs/__init__.py
- liquid_node/jobs/liquid.py
- liquid_node/nomad.py
- liquid_node/util.py
- templates/hypothesis.nomad
- templates/liquid-createuser.nomad
- templates/scripts/create_hypothesis_user.py
- templates/scripts/create_rocket_user.py
- templates/scripts/createuser.sh
> Create user in all apps after it has been created in core

- templates/liquid.nomad
> add nomad url env to core

- liquid_node/commands.py
- liquid_node/nomad.py
> Ignore unavailable resources

- templates/rocketchat-init-replica-set.sh
> Fix rocketchat mongodb replica config

- liquid_node/commands.py
> add command to remove dead nodes

- templates/rocketchat-deps.nomad
> use static port for rocketchat mongo

- liquid_node/jobs/liquid.py
- templates/_lib.hcl
- templates/authproxy-redis.nomad
- templates/liquid.nomad
> fix deploy order and use load balancer for authproxy redis

- examples/liquid.ini
- liquid_node/configuration.py
- templates/hoover.nomad
> add debug delay setting for searches

- examples/liquid.ini
- liquid_node/configuration.py
- templates/hoover-nginx.nomad
add environment variables to UI-job to control async search behaviour
> add envs for ui

- liquid_node/configuration.py
> improve collection name validation

- examples/liquid.ini
- liquid_node/backup.py
- liquid_node/commands.py
> add wikijs pg to backup

- templates/wikijs.nomad
closes CRJI/EIC#1003
see https://github.com/liquidinvestigations/wiki.js/pull/3 for the PR that requires these changes
> add wikijs envs in a .env file

- scripts/export-dokuwiki-into-wikijs.sh
> add script to to import into wikijs from dokuwiki

- liquid_node/configuration.py
- liquid_node/jobs/liquid.py
- scripts/migrate_groups.sh
- templates/_lib.hcl
- templates/liquid-creategroup.nomad
- templates/liquid-createuser.nomad
- templates/liquid-deletegroup.nomad
- templates/scripts/creategroup.sh
- templates/scripts/deletegroup.sh
- templates/wikijs.nomad
> Groups sync

- scripts/create-wikijs-certs.sh
> add script to create wikijs certificates

- .gitignore
- CHANGELOG.md
- ci/conf/1-no-collections.ini
- ci/conf/1-with-collections-stopped.ini
- ci/run-integration-tests.sh
- ci/tests/1-hoover
- ci/tests/2-backup-restore
- ci/tests/3-integration
- ci/ui/run_ui_tests.sh
- liquid
- liquid_node/commands.py
- liquid_node/configuration.py
- liquid_node/jobs/__init__.py
- liquid_node/jobs/hoover.py
- liquid_node/jsonapi.py
- liquid_node/nomad.py
- liquid_node/util.py
- production-versions.ini
- scripts/create-wikijs-certs.sh
- scripts/dump-wikijs.sh
- scripts/update-dashboards-uptrace.sh
- templates/hoover-deps.nomad
- templates/hoover-migrate.nomad
- templates/liquid.nomad
- templates/rocketchat-init-replica-set.sh
- update-0.13.1.sh
closes https://github.com/CRJI/EIC/issues/1057, https://github.com/CRJI/EIC/issues/534, https://github.com/CRJI/EIC/issues/321, https://github.com/CRJI/EIC/issues/1050
- add status page info to home page configs
- print container logs in deploy command if container restarts in a loop
- print container logs in deploy command if batch job takes a very long time
- deploy command: log all outputs to disk under the directory `.logs`
- automatically reset ES readonly mode on deployment, and error directly if disk is full
> Deployment improvements

- templates/_lib.hcl
fixes this problem: https://github.com/oauth2-proxy/oauth2-proxy/issues/844
> fix authproxy redirects

- templates/nextcloud28-entrypoint.sh
> fix entrypoint to make php changes work

- liquid_node/backup.py
> ignore collectiondocumenthit when backing up pg database
